-- begin DAEX_CERTIFICATE
alter table DAEX_CERTIFICATE add constraint FK_DAEX_CERTIFICATE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references DAEX_EMPLOYEE(ID)^
create unique index IDX_DAEX_CERTIFICATE_UK_NUMBER_ on DAEX_CERTIFICATE (NUMBER_) where DELETE_TS is null ^
create index IDX_DAEX_CERTIFICATE_ON_EMPLOYEE on DAEX_CERTIFICATE (EMPLOYEE_ID)^
-- end DAEX_CERTIFICATE
-- begin DAEX_REMARK_ANSWER
alter table DAEX_REMARK_ANSWER add constraint FK_DAEX_REMARK_ANSWER_ON_RPD_FILE foreign key (RPD_FILE_ID) references DAEX_RPD_FILE(ID)^
create index IDX_DAEX_REMARK_ANSWER_ON_RPD_FILE on DAEX_REMARK_ANSWER (RPD_FILE_ID)^
-- end DAEX_REMARK_ANSWER
-- begin DAEX_RPD_FILE
alter table DAEX_RPD_FILE add constraint FK_DAEX_RPD_FILE_ON_RPD foreign key (RPD_ID) references DAEX_RPD(ID)^
create index IDX_DAEX_RPD_FILE_ON_RPD on DAEX_RPD_FILE (RPD_ID)^
-- end DAEX_RPD_FILE
-- begin DAEX_RPD
alter table DAEX_RPD add constraint FK_DAEX_RPD_ON_HEAD_RPD foreign key (HEAD_RPD_ID) references DAEX_HEAD_RPD(ID)^
alter table DAEX_RPD add constraint FK_DAEX_RPD_ON_EXPERTISE_RPD foreign key (EXPERTISE_RPD_ID) references DAEX_EXPERTISE(ID)^
create index IDX_DAEX_RPD_ON_HEAD_RPD on DAEX_RPD (HEAD_RPD_ID)^
create index IDX_DAEX_RPD_ON_EXPERTISE_RPD on DAEX_RPD (EXPERTISE_RPD_ID)^
-- end DAEX_RPD
-- begin DAEX_ACCESS_SETTINGS
alter table DAEX_ACCESS_SETTINGS add constraint FK_DAEX_ACCESS_SETTINGS_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table DAEX_ACCESS_SETTINGS add constraint FK_DAEX_ACCESS_SETTINGS_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references DAEX_EMPLOYEE(ID)^
alter table DAEX_ACCESS_SETTINGS add constraint FK_DAEX_ACCESS_SETTINGS_ON_EXPERTISE_ACCESS_SETTINGS foreign key (EXPERTISE_ACCESS_SETTINGS_ID) references DAEX_EXPERTISE(ID)^
create index IDX_DAEX_ACCESS_SETTINGS_ON_USER on DAEX_ACCESS_SETTINGS (USER_ID)^
create index IDX_DAEX_ACCESS_SETTINGS_ON_EMPLOYEE on DAEX_ACCESS_SETTINGS (EMPLOYEE_ID)^
create index IDX_DAEX_ACCESS_SETTINGS_ON_EXPERTISE_ACCESS_SETTINGS on DAEX_ACCESS_SETTINGS (EXPERTISE_ACCESS_SETTINGS_ID)^
-- end DAEX_ACCESS_SETTINGS
-- begin DAEX_EXPERTISE
alter table DAEX_EXPERTISE add constraint FK_DAEX_EXPERTISE_ON_LEADER_EMPLOYEE foreign key (LEADER_EMPLOYEE_ID) references DAEX_EMPLOYEE(ID)^
alter table DAEX_EXPERTISE add constraint FK_DAEX_EXPERTISE_ON_CUSTOMER_MAIN foreign key (CUSTOMER_MAIN_ID) references DAEX_CUSTOMER(ID)^
alter table DAEX_EXPERTISE add constraint FK_DAEX_EXPERTISE_ON_CUSTOMER_TECH foreign key (CUSTOMER_TECH_ID) references DAEX_CUSTOMER(ID)^
create index IDX_DAEX_EXPERTISE_ON_LEADER_EMPLOYEE on DAEX_EXPERTISE (LEADER_EMPLOYEE_ID)^
create index IDX_DAEX_EXPERTISE_ON_CUSTOMER_MAIN on DAEX_EXPERTISE (CUSTOMER_MAIN_ID)^
create index IDX_DAEX_EXPERTISE_ON_CUSTOMER_TECH on DAEX_EXPERTISE (CUSTOMER_TECH_ID)^
-- end DAEX_EXPERTISE
-- begin DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_LINK
alter table DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_INCDOCFILDES_ON_INCOMING_DOCUMENT foreign key (INCOMING_DOCUMENT_ID) references DAEX_INCOMING_DOCUMENT(ID)^
alter table DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_LINK add constraint FK_INCDOCFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_LINK
-- begin DAEX_RPD_FILE_FILE_DESCRIPTOR_LINK
alter table DAEX_RPD_FILE_FILE_DESCRIPTOR_LINK add constraint FK_RPDFILFILDES_ON_R_P_D_FILE foreign key (R_P_D_FILE_ID) references DAEX_RPD_FILE(ID)^
alter table DAEX_RPD_FILE_FILE_DESCRIPTOR_LINK add constraint FK_RPDFILFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end DAEX_RPD_FILE_FILE_DESCRIPTOR_LINK
-- begin DAEX_EXPERTISE_FILE_DESCRIPTOR_LINK
alter table DAEX_EXPERTISE_FILE_DESCRIPTOR_LINK add constraint FK_EXPFILDES_ON_EXPERTISE foreign key (EXPERTISE_ID) references DAEX_EXPERTISE(ID)^
alter table DAEX_EXPERTISE_FILE_DESCRIPTOR_LINK add constraint FK_EXPFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end DAEX_EXPERTISE_FILE_DESCRIPTOR_LINK
-- begin DAEX_REMARK_ANSWER_FILE_DESCRIPTOR_LINK
alter table DAEX_REMARK_ANSWER_FILE_DESCRIPTOR_LINK add constraint FK_REMANSFILDES_ON_REMARK_ANSWER foreign key (REMARK_ANSWER_ID) references DAEX_REMARK_ANSWER(ID)^
alter table DAEX_REMARK_ANSWER_FILE_DESCRIPTOR_LINK add constraint FK_REMANSFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
-- end DAEX_REMARK_ANSWER_FILE_DESCRIPTOR_LINK
-- begin DAEX_EMPLOYEE
alter table DAEX_EMPLOYEE add constraint FK_DAEX_EMPLOYEE_ON_USER_SYS foreign key (USER_SYS_ID) references SEC_USER(ID)^
create index IDX_DAEX_EMPLOYEE_ON_USER_SYS on DAEX_EMPLOYEE (USER_SYS_ID)^
-- end DAEX_EMPLOYEE
-- begin DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR
alter table DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR add constraint FK_DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_ON_INCOMING_DOCUMENT foreign key (INCOMING_DOCUMENT_ID) references DAEX_INCOMING_DOCUMENT(ID)^
alter table DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR add constraint FK_DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
create index IDX_DAEX_INCOMINDOCUMENFILEDESCRIP_ON_INCOMING_DOCUMENT on DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR (INCOMING_DOCUMENT_ID)^
create index IDX_DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR_ON_FILE_DESCRIPTOR on DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR (FILE_DESCRIPTOR_ID)^
-- end DAEX_INCOMING_DOCUMENT_FILE_DESCRIPTOR
